namespace :gastosgem do

  desc "initialize content db (initial load countries)"
  task :initialize_contents => :environment do |t|
    puts "please confirm you initialize contents  (type 'yes' to confirm, or anything else to skip)"
    s_answer=$stdin.gets
    if s_answer.chomp == 'yes'
      init_countries      
    else
      puts "initialize_contents skipped"
     end
  end #task do

  # In UTF-8
  def init_countries
    [
      "Afganistán",
      "Islas Åland",
      "Albania",
      "Alemania",
      "Andorra",
      "Angola",
      "Anguilla",
      "Antártida",
      "Antigua y Barbuda",
      "Antillas Holandesas",
      "Arabia Saudí",
      "Argelia",
      "Argentina",
      "Armenia",
      "Aruba",
      "Australia",
      "Austria",
      "Azerbaiyán",
      "Bahamas",
      "Bahréin",
      "Bangladesh",
      "Barbados",
      "Bielorrusia",
      "Bélgica",
      "Belice",
      "Benin",
      "Bermudas",
      "Bhután",
      "Bolivia",
      "Bosnia y Herzegovina",
      "Botsuana",
      "Isla Bouvet",
      "Brasil",
      "Brunéi",
      "Bulgaria",
      "Burkina Faso",
      "Burundi",
      "Cabo Verde",
      "Islas Caimán",
      "Camboya",
      "Camerún",
      "Canadá",
      "República Centroafricana",
      "Chad",
      "República Checa",
      "Chile",
      "China",
      "Chipre",
      "Islas Cocos",
      "Colombia",
      "Comoras",
      "República del Congo",
      "República Democrática del Congo",
      "Islas Cook",
      "Corea del Norte",
      "Corea del Sur",
      "Costa de Marfil",
      "Costa Rica",
      "Croacia",
      "Cuba",
      "Dinamarca",
      "Dominica",
      "República Dominicana",
      "Ecuador",
      "Egipto",
      "El Salvador",
      "Emiratos Árabes Unidos",
      "Eritrea",
      "Eslovaquia",
      "Eslovenia",
      "España",
      "Estados Unidos",
      "Islas ultramarinas de Estados Unidos",
      "Estonia",
      "Etiopía",
      "Islas Feroe",
      "Filipinas",
      "Finlandia",
      "Fiyi",
      "Francia",
      "Gabón",
      "Gambia",
      "Georgia",
      "Islas Georgias del Sur y Sandwich del Sur",
      "Ghana",
      "Gibraltar",
      "Granada",
      "Grecia",
      "Groenlandia",
      "Guadalupe",
      "Guam",
      "Guatemala",
      "Guayana Francesa",
      "Guernesey",
      "Guinea",
      "Guinea Ecuatorial",
      "Guinea-Bissau",
      "Guyana",
      "Haití",
      "Islas Heard y McDonald",
      "Honduras",
      "Hong Kong",
      "Hungría",
      "India",
      "Indonesia",
      "Irán",
      "Iraq",
      "Irlanda",
      "Islandia",
      "Israel",
      "Italia",
      "Jamaica",
      "Japón",
      "Jersey",
      "Jordania",
      "Kazajistán",
      "Kenia",
      "Kirguistán",
      "Kiribati",
      "Kuwait",
      "Laos",
      "Lesotho",
      "Letonia",
      "Líbano",
      "Liberia",
      "Libia",
      "Liechtenstein",
      "Lituania",
      "Luxemburgo",
      "Macao",
      "ARY Macedonia",
      "Madagascar",
      "Malasia",
      "Malawi",
      "Maldivas",
      "Malí",
      "Malta",
      "Islas Malvinas",
      "Isla de Man",
      "Islas Marianas del Norte",
      "Marruecos",
      "Islas Marshall",
      "Martinica",
      "Mauricio",
      "Mauritania",
      "Mayotte",
      "México",
      "Micronesia",
      "Moldavia",
      "Mónaco",
      "Mongolia",
      "Montserrat",
      "Mozambique",
      "Myanmar",
      "Namibia",
      "Nauru",
      "Isla de Navidad",
      "Nepal",
      "Nicaragua",
      "Níger",
      "Nigeria",
      "Niue",
      "Isla Norfolk",
      "Noruega",
      "Nueva Caledonia",
      "Nueva Zelanda",
      "Omán",
      "Países Bajos",
      "Pakistán",
      "Palau",
      "Palestina",
      "Panamá",
      "Papúa Nueva Guinea",
      "Paraguay",
      "Perú",
      "Islas Pitcairn",
      "Polinesia Francesa",
      "Polonia",
      "Portugal",
      "Puerto Rico",
      "Qatar",
      "Reino Unido",
      "Reunión",
      "Ruanda",
      "Rumania",
      "Rusia",
      "Sahara Occidental",
      "Islas Salomón",
      "Samoa",
      "Samoa Americana",
      "San Cristóbal y Nevis",
      "San Marino",
      "San Pedro y Miquelón",
      "San Vicente y las Granadinas",
      "Santa Helena",
      "Santa Lucía",
      "Santo Tomé y Príncipe",
      "Senegal",
      "Serbia y Montenegro",
      "Seychelles",
      "Sierra Leona",
      "Singapur",
      "Siria",
      "Somalia",
      "Sri Lanka",
      "Suazilandia",
      "Sudáfrica",
      "Sudán",
      "Suecia",
      "Suiza",
      "Surinam",
      "Svalbard y Jan Mayen",
      "Tailandia",
      "Taiwán",
      "Tanzania",
      "Tayikistán",
      "Territorio Británico del Océano Índico",
      "Territorios Australes Franceses",
      "Timor Oriental",
      "Togo",
      "Tokelau",
      "Tonga",
      "Trinidad y Tobago",
      "Túnez",
      "Islas Turcas y Caicos",
      "Turkmenistán",
      "Turquía",
      "Tuvalu",
      "Ucrania",
      "Uganda",
      "Uruguay",
      "Uzbekistán",
      "Vanuatu",
      "Ciudad del Vaticano",
      "Venezuela",
      "Vietnam",
      "Islas Vírgenes Británicas",
      "Islas Vírgenes de los Estados Unidos",
      "Wallis y Futuna",
      "Yemen",
      "Yibuti",
      "Zambia",
      "Zimbabue"
    ].each do |name|
      Country.create(:name => name)
    end
  end

end #namespace

# Database tables ordered depending on the fks
my_fixtures = [:countries, :enterprises, :users, :projects, :expense_types, :expenses, :payments]

ENV['FIXTURES'] = my_fixtures.join(',')

namespace :db do
  namespace :fixtures do
    desc "Load fixtures into the current environment's database in one transaction.  Load specific fixtures using FIXTURES=x,y"
    task :load_all => :environment do
      require 'active_record/fixtures'
      ActiveRecord::Base.establish_connection(RAILS_ENV.to_sym)
      @connection = ActiveRecord::Base.connection
      @connection.update "SET FOREIGN_KEY_CHECKS = 0", 'Fixtures deactivate foreign key checks.';
      fixture_files = (ENV['FIXTURES'] ? ENV['FIXTURES'].split(/,/) : Dir.glob(File.join(RAILS_ROOT, 'test', 'fixtures', '*.{yml,csv}'))).collect {|fixture_file| File.basename(fixture_file, '.*') }
      Fixtures.create_fixtures('test/fixtures', fixture_files)
      @connection.update "SET FOREIGN_KEY_CHECKS = 1", 'Fixtures deactivate foreign key checks.';
    end
  end
end

# Add another action to task db:test:prepare so that it automatically calls db:fixtures:load_all
# after recreating the test db
namespace :db do
  namespace :test do
    task :prepare => :environment do
      RAILS_ENV='test'
      Rake::Task['db:fixtures:load_all'].invoke
    end
  end
end

